site_name: http://epg.best/23b73-2af6vb.xml.gz
pages:
  - Usage: index.md
  - Authentication: authentication.md
  - Countries and channels: channels.md
  - Programmes: programmes.md
  - User data: user.md
  - User links: links.md 
  - Changelog: changelog.md
theme: readthedocs
